openapi: "3.0.0"
info:
  title: Tshirt store API
  description: API for managing a tshirt store
  version: 1.1.0
  contact:
    email: mahbub@tesla.com
    url: https://www.tesla.com

servers:
  - url: "{protocol}://localhost:{port}/api/v1"
    description: "The development API server"
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - "http"
          - "https"
        default: "http"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /dummy:
    get:
      tags:
        - Home
      summary: Dummy endpoint
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: string
                example: "Hello world"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: string
                example: "Bad request"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
